// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR1_35ZtEt5OC9wqYbl8rpbJta6vrhOgM',
    appId: '1:395525310408:web:c97553d900b2a0984562fd',
    messagingSenderId: '395525310408',
    projectId: 'sewami-92617',
    authDomain: 'sewami-92617.firebaseapp.com',
    storageBucket: 'sewami-92617.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRdJu-yZ6xlVrRPMNNd2XW-0lVFqxCYA',
    appId: '1:395525310408:android:89664e82bb384bab4562fd',
    messagingSenderId: '395525310408',
    projectId: 'sewami-92617',
    storageBucket: 'sewami-92617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9JEtmzLBOVYh2mn0EZVnXp2YDQfznGa0',
    appId: '1:395525310408:ios:1231904f6732b7784562fd',
    messagingSenderId: '395525310408',
    projectId: 'sewami-92617',
    storageBucket: 'sewami-92617.firebasestorage.app',
    iosBundleId: 'com.example.apkSewami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9JEtmzLBOVYh2mn0EZVnXp2YDQfznGa0',
    appId: '1:395525310408:ios:1231904f6732b7784562fd',
    messagingSenderId: '395525310408',
    projectId: 'sewami-92617',
    storageBucket: 'sewami-92617.firebasestorage.app',
    iosBundleId: 'com.example.apkSewami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR1_35ZtEt5OC9wqYbl8rpbJta6vrhOgM',
    appId: '1:395525310408:web:1b3035e88f6b8d524562fd',
    messagingSenderId: '395525310408',
    projectId: 'sewami-92617',
    authDomain: 'sewami-92617.firebaseapp.com',
    storageBucket: 'sewami-92617.firebasestorage.app',
  );

}